import 'package:get_it/get_it.dart';
import 'package:vendoorr/core/service/api.dart';
import 'package:vendoorr/core/service/authenticationService.dart';
import 'package:vendoorr/core/service/printingService.dart';
import 'package:vendoorr/core/service/sharedPreferences.dart';
import 'package:vendoorr/core/viewModels/ProductViewModel.dart';
import 'package:vendoorr/core/viewModels/addBranchModel.dart';
import 'package:vendoorr/core/viewModels/addCategoryModel.dart';
import 'package:vendoorr/core/viewModels/addContactViewModel.dart';
import 'package:vendoorr/core/viewModels/addDefinedExpenseViewModel.dart';
import 'package:vendoorr/core/viewModels/addItemsViewModel.dart';
import 'package:vendoorr/core/viewModels/addNewUserRoleModel.dart';
import 'package:vendoorr/core/viewModels/addProductViewModel.dart';
import 'package:vendoorr/core/viewModels/addStaffViewModel.dart';
import 'package:vendoorr/core/viewModels/addUndefinedExpnesModel.dart';
import 'package:vendoorr/core/viewModels/analysisTopViewModel.dart';
import 'package:vendoorr/core/viewModels/authViewModel.dart';
import 'package:vendoorr/core/viewModels/avtivityViewModel.dart';
import 'package:vendoorr/core/viewModels/branchDetailsViewModel.dart';
import 'package:vendoorr/core/viewModels/branchTopViewModel.dart';
import 'package:vendoorr/core/viewModels/branch_productsViewModel.dart';
import 'package:vendoorr/core/viewModels/branchesViewModel.dart';
import 'package:vendoorr/core/viewModels/consignmentViewModel.dart';
import 'package:vendoorr/core/viewModels/contactViewModel.dart';
import 'package:vendoorr/core/viewModels/createConsignmentViewModel.dart';
import 'package:vendoorr/core/viewModels/createTabViewModel.dart';
import 'package:vendoorr/core/viewModels/creditAndDebitViewModel.dart';
import 'package:vendoorr/core/viewModels/creditModalViewModel.dart';
import 'package:vendoorr/core/viewModels/creditOrDebitModalViewModel.dart';
import 'package:vendoorr/core/viewModels/dashboardViewModel.dart';
import 'package:vendoorr/core/viewModels/discountModalViewModel.dart';
import 'package:vendoorr/core/viewModels/editBranchViewModel.dart';
import 'package:vendoorr/core/viewModels/editCategoryModel.dart';
import 'package:vendoorr/core/viewModels/editProductViewModel.dart';
import 'package:vendoorr/core/viewModels/editStaffViewModel.dart';
import 'package:vendoorr/core/viewModels/editUserRoleModel.dart';
import 'package:vendoorr/core/viewModels/expensesViewModel.dart';
import 'package:vendoorr/core/viewModels/firstPrinterAssignViewModel.dart';
import 'package:vendoorr/core/viewModels/homeViewModel.dart';
import 'package:vendoorr/core/viewModels/loginViewModel.dart';
import 'package:vendoorr/core/viewModels/ordersViewModel.dart';
import 'package:vendoorr/core/viewModels/placeOrderViewModel.dart';
import 'package:vendoorr/core/viewModels/printDebtsandCreditsViewModel.dart';
import 'package:vendoorr/core/viewModels/printingViewModel.dart';
import 'package:vendoorr/core/viewModels/rootProvider.dart';
import 'package:vendoorr/core/viewModels/salesViewModel.dart';
import 'package:vendoorr/core/viewModels/selectDateRangeViewModel.dart';
import 'package:vendoorr/core/viewModels/sellOrderModel.dart';
import 'package:vendoorr/core/viewModels/settingsViewModel.dart';
import 'package:vendoorr/core/viewModels/snackViewModel.dart';
import 'package:vendoorr/core/viewModels/staffRoleViewModel.dart';
import 'package:vendoorr/core/viewModels/staffViewModel.dart';

GetIt sl = GetIt.instance;

void setupLocator() {
  sl.registerLazySingleton(() => AuthenticationService());
  sl.registerLazySingleton(() => PrintingService());
  sl.registerFactory(() => StaffRoleViewModel());
  sl.registerLazySingleton(() => Api());
  sl.registerFactory(() => AuthViewModel());
  sl.registerFactory(() => LoginViewModel());
  sl.registerFactory(() => HomeViewModel());
  sl.registerFactory(() => BProductViewModel());
  sl.registerFactory(() => BranchDetailsViewModel());
  sl.registerFactory(() => ProductViewModel());
  sl.registerLazySingleton(() => DashBoardViewModel());
  sl.registerLazySingleton(() => BranchTopViewModel());
  sl.registerLazySingleton(() => BranchesViewModel());
  sl.registerLazySingleton(() => SharedPreferencesService());
  sl.registerLazySingleton(() => RootProvider());
  sl.registerLazySingleton(() => OrdersViewModel());
  sl.registerLazySingleton(() => SalesViewModel());
  sl.registerLazySingleton(() => SnackViewModel());
  sl.registerLazySingleton(() => StaffViewModel());
  sl.registerLazySingleton(() => ActivitiesViewModel());
  sl.registerLazySingleton(() => ExpensesViewModel());
  sl.registerLazySingleton(() => CreditViewModel());
  sl.registerLazySingleton(() => ContactsViewModel());
  sl.registerFactory(() => SettingsViewModel());
  sl.registerFactory(() => EditStaffViewModel());
  sl.registerFactory(() => PlaceOrderModel());
  sl.registerFactory(() => AddBranchModel());
  sl.registerFactory(() => AddCategoryModel());
  sl.registerFactory(() => EditBranchViewModel());
  sl.registerFactory(() => EditCategoryModel());
  sl.registerFactory(() => PrintingViewModel());
  sl.registerFactory(() => AddUserRoleModel());
  sl.registerFactory(() => EditUserRoleModel());
  sl.registerFactory(() => AddProductViewModel());
  sl.registerFactory(() => EditProductViewModel());
  sl.registerFactory(() => ConsignmentViewModel());
  sl.registerFactory(() => CreateConsignmentViewModel());
  sl.registerFactory(() => DiscountModalViewModel());
  sl.registerFactory(() => CreateTabViewModel());
  sl.registerFactory(() => SellOrderViewModel());
  sl.registerFactory(() => AddDefinedExpenseViewModel());
  sl.registerFactory(() => AddUndefinedExpenseModel());
  sl.registerFactory(() => FirstAssignViewModel());
  sl.registerFactory(() => AddItemViewModel());
  sl.registerFactory(() => CreditModalViewModel());
  sl.registerFactory(() => CreditOrDebitModalViewModel());
  sl.registerFactory(() => AddContactViewModel());
  sl.registerFactory(() => AddStaffViewModel());
  sl.registerFactory(() => AnalysisViewModel());
  sl.registerFactory(() => PrintDebtorsAndCreditorsViewModel());
  sl.registerFactory(() => SelectDateRangeViewModel());
}
